/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lendle.courses.wp.dialogsample;

import javax.swing.JOptionPane;

/**
 *
 * @author lendle
 */
public class ShowMessageDialogSample extends javax.swing.JFrame {

    /**
     * Creates new form ShowMessageDialogSample
     */
    public ShowMessageDialogSample() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DefaultButton = new javax.swing.JButton();
        ErrorButton = new javax.swing.JButton();
        InformationButton = new javax.swing.JButton();
        PlainButton = new javax.swing.JButton();
        QuestionButton = new javax.swing.JButton();
        WarningButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 1));

        DefaultButton.setText("Default");
        DefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DefaultButton);

        ErrorButton.setText("Error");
        ErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ErrorButton);

        InformationButton.setText("Information");
        InformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InformationButton);

        PlainButton.setText("Plain");
        PlainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PlainButton);

        QuestionButton.setText("Question");
        QuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(QuestionButton);

        WarningButton.setText("Warning");
        WarningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarningButtonActionPerformed(evt);
            }
        });
        getContentPane().add(WarningButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hello");
    }//GEN-LAST:event_DefaultButtonActionPerformed

    private void ErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hello","ERROR!",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ErrorButtonActionPerformed

    private void InformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hello","INFORMATION!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_InformationButtonActionPerformed

    private void PlainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlainButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hello","PLAIN!",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_PlainButtonActionPerformed

    private void QuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hello","QUESTION!",JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_QuestionButtonActionPerformed

    private void WarningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarningButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hello","WARNING!",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_WarningButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMessageDialogSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMessageDialogSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMessageDialogSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMessageDialogSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowMessageDialogSample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DefaultButton;
    private javax.swing.JButton ErrorButton;
    private javax.swing.JButton InformationButton;
    private javax.swing.JButton PlainButton;
    private javax.swing.JButton QuestionButton;
    private javax.swing.JButton WarningButton;
    // End of variables declaration//GEN-END:variables
}
